### ISSUE TITLE
Fedora linux ( kde ) linking problems

### ISSUE THREAD

**Issue by blalyasar** [GlistEngine/GlistEngine#66]
.Hocam Build den sonra linking hatası alıyorum.  eclipse kullanmadan cmake ile bunu çözebilirmiyiz. 
Dün readme.md pull requestini Dün manuel kurulum ile yapmaya çalısmıstım sağ olun tüm dosyaları ayrı ayrı gondermıssınız cloneladım ama halen sıkıntı yasıyorum..

 $ tree -d -L 3
.
└── glist
    ├── GlistEngine
    │   ├── apps
    │   ├── docs
    │   ├── engine
    │   ├── libs
    │   ├── plugins
    │   └── samples
    ├── myglistapp
    │   └── glistapp
    └── zbin
        └── glistzbin-linux

12 directories
$ tree -d -L 4
.
└── glist
    ├── GlistEngine
    │   ├── apps
    │   │   └── giaEmpty
    │   ├── docs
    │   ├── engine
    │   │   ├── base
    │   │   ├── core
    │   │   ├── graphics
    │   │   ├── media
    │   │   ├── types
    │   │   └── utils
    │   ├── libs
    │   │   ├── fmod
    │   │   ├── ghc
    │   │   ├── stb
    │   │   └── utf8
    │   ├── plugins
    │   │   └── gipEmpty
    │   └── samples
    │       ├── gisEmpty
    │       ├── gisImage
    │       ├── gisLight
    │       ├── gisSkinnedMesh
    │       └── gisVbo
    ├── myglistapp
    │   └── glistapp
    │       ├── assets
    │       ├── CMakeFiles
    │       └── src
    └── zbin
        └── glistzbin-linux
            ├── eclipse
            └── mingw64

34 directories
cd ~/dev/glist/GlistEngine/samples/gisEmpty
cmake . && make
....
 Linking CXX shared library libGlistEngine.so
Using built-in specs.
COLLECT_GCC=/usr/bin/c++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20201125 (Red Hat 10.2.1-9) (GCC) 

Aynı şekilde 
dev/glist/GlistEngine/engine
cmake && make yapınca 

[ 97%] Building CXX object CMakeFiles/GlistEngine.dir/core/gGLFWWindow.cpp.o
[100%] Linking CXX shared library libGlistEngine.so
Using built-in specs.
COLLECT_GCC=/usr/bin/c++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20201125 (Red Hat 10.2.1-9) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/10/:/usr/libexec/gcc/x86_64-redhat-linux/10/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/10/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/10/:/usr/lib/gcc/x86_64-redhat-linux/10/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/10/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-fPIC' '-v' '-shared' '-o' 'libGlistEngine.so' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/10/collect2 -plugin /usr/libexec/gcc/x86_64-redhat-linux/10/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper -plugin-opt=-fresolution=/tmp/ccqpsV0n.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -shared -o libGlistEngine.so /usr/lib/gcc/x86_64-redhat-linux/10/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/10/crtbeginS.o -L/usr/lib/gcc/x86_64-redhat-linux/10 -L/usr/lib/gcc/x86_64-redhat-linux/10/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/10/../../.. --no-as-needed --gc-sections --unresolved-symbols=report-all -soname libGlistEngine.so CMakeFiles/GlistEngine.dir/types/gColor.cpp.o CMakeFiles/GlistEngine.dir/utils/gUtils.cpp.o CMakeFiles/GlistEngine.dir/utils/gFile.cpp.o CMakeFiles/GlistEngine.dir/graphics/gShader.cpp.o CMakeFiles/GlistEngine.dir/core/gObject.cpp.o CMakeFiles/GlistEngine.dir/core/gRenderer.cpp.o CMakeFiles/GlistEngine.dir/core/gRenderObject.cpp.o CMakeFiles/GlistEngine.dir/graphics/gTexture.cpp.o CMakeFiles/GlistEngine.dir/graphics/gImage.cpp.o CMakeFiles/GlistEngine.dir/graphics/gSkybox.cpp.o CMakeFiles/GlistEngine.dir/graphics/gNode.cpp.o CMakeFiles/GlistEngine.dir/graphics/gLight.cpp.o CMakeFiles/GlistEngine.dir/graphics/gCamera.cpp.o CMakeFiles/GlistEngine.dir/graphics/gFont.cpp.o CMakeFiles/GlistEngine.dir/graphics/gMaterial.cpp.o CMakeFiles/GlistEngine.dir/graphics/gMesh.cpp.o CMakeFiles/GlistEngine.dir/graphics/gSkinnedMesh.cpp.o CMakeFiles/GlistEngine.dir/graphics/gModel.cpp.o CMakeFiles/GlistEngine.dir/graphics/primitives/gPlane.cpp.o CMakeFiles/GlistEngine.dir/graphics/primitives/gBox.cpp.o CMakeFiles/GlistEngine.dir/graphics/gVbo.cpp.o CMakeFiles/GlistEngine.dir/graphics/gFbo.cpp.o CMakeFiles/GlistEngine.dir/graphics/gRay.cpp.o CMakeFiles/GlistEngine.dir/graphics/gBoundingBox.cpp.o CMakeFiles/GlistEngine.dir/graphics/gRect.cpp.o CMakeFiles/GlistEngine.dir/core/gAppObject.cpp.o CMakeFiles/GlistEngine.dir/base/gBasePlugin.cpp.o CMakeFiles/GlistEngine.dir/media/gBaseSound.cpp.o CMakeFiles/GlistEngine.dir/media/gFmodSound.cpp.o CMakeFiles/GlistEngine.dir/base/gBaseApp.cpp.o CMakeFiles/GlistEngine.dir/base/gBaseCanvas.cpp.o CMakeFiles/GlistEngine.dir/core/gBaseWindow.cpp.o CMakeFiles/GlistEngine.dir/core/gCanvasManager.cpp.o CMakeFiles/GlistEngine.dir/core/gAppManager.cpp.o CMakeFiles/GlistEngine.dir/core/backward.cpp.o CMakeFiles/GlistEngine.dir/core/gGLFWWindow.cpp.o -rpath /home/flankes/dev/glist/GlistEngine/engine/../../zbin/glistzbin-linux/mingw64/lib ../../zbin/glistzbin-linux/mingw64/lib/libfmodL.so ../../zbin/glistzbin-linux/mingw64/lib/libfmod.so ../../zbin/glistzbin-linux/mingw64/lib/libassimp.so ../../zbin/glistzbin-linux/mingw64/lib/libfreetype.so ../../zbin/glistzbin-linux/mingw64/lib/libpng.so ../../zbin/glistzbin-linux/mingw64/lib/libglfw.so -lGL -lGLEW -lstdc++ -lm -lgcc_s -lc -lgcc_s /usr/lib/gcc/x86_64-redhat-linux/10/crtendS.o /usr/lib/gcc/x86_64-redhat-linux/10/../../../../lib64/crtn.o
/usr/bin/ld: ../../zbin/glistzbin-linux/mingw64/lib/libfmodL.so: .dynsym local symbol at index 2 (>= sh_info of 2)
/usr/bin/ld: ../../zbin/glistzbin-linux/mingw64/lib/libfmodL.so: .dynsym local symbol at index 3 (>= sh_info of 2)
/usr/bin/ld: ../../zbin/glistzbin-linux/mingw64/lib/libfmodL.so: .dynsym local symbol at index 4 (>= sh_info of 2)
/usr/bin/ld: ../../zbin/glistzbin-linux/mingw64/lib/libfmod.so: .dynsym local symbol at index 2 (>= sh_info of 2)
/usr/bin/ld: ../../zbin/glistzbin-linux/mingw64/lib/libfmod.so: .dynsym local symbol at index 3 (>= sh_info of 2)
/usr/bin/ld: ../../zbin/glistzbin-linux/mingw64/lib/libfmod.so: .dynsym local symbol at index 4 (>= sh_info of 2)
/usr/bin/ld:../../zbin/glistzbin-linux/mingw64/lib/libassimp.so: file format not recognized; treating as linker script
/usr/bin/ld:../../zbin/glistzbin-linux/mingw64/lib/libassimp.so:1: syntax error
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/GlistEngine.dir/build.make:634: libGlistEngine.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/GlistEngine.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
  pwd
~/dev/glist/GlistEngine/engine
 $ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: ~/dev/glist/GlistEngine/engine

**Comment by noyanc** [comment]
Paylaştığınız loglarda, kuruluma eklediğimiz önceden derlenmiş (prebuilt) Assimp kütüphanesinin okunamadığını görüyorum:
`/usr/bin/ld:../../zbin/glistzbin-linux/mingw64/lib/libassimp.so: file format not recognized; treating as linker script`
`/usr/bin/ld:../../zbin/glistzbin-linux/mingw64/lib/libassimp.so:1: syntax error`

PR'da gönderdiğiniz "sudo dnf install assimp assimp-devel" komutu problemi düzeltti mi?

**Comment by blalyasar** [comment]
Bu clone'lanan dosyaların içinde vardır diye düşündüm ondan dolayı issue açtım . Hepsini çok ayrıntılı inceleyemedim. Assimp kutuphanesi kurulu bu aradaç  Manuel olarak kurmayı başaramadım . maalesef tekrar bir deneme yapacagım.
